#!/bin/sh
#
# @name Solo
#
# @type Quadrotor
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_PITCHRATE_P 0.15
	param set MC_ROLLRATE_P 0.15
fi

param set EKF2_GPS_P_NOISE 2.0
param set EKF2_EVP_NOISE 0.01
param set EKF2_AID_MASK 9
param set EKF2_HGT_MODE 0
param set EKF2_EV_DELAY 10
param set MPC_Z_VEL_MAX_DN 0.5
param set MPC_Z_VEL_MAX_UP 1.0
param set MPC_XY_VEL_MAX 0.8

set MIXER quad_x